name: 'jFrog CLI for Artifactory'
author: 'Advanced Toolchain'
description: 'Run jFrog CLI commands for Artifactory'
inputs:
  url:
    description: 'URL of Artifactory instance'
    required: true
  credentials type:
    description: 'Type of authentication to use. Must be one of username, apikey or accesstoken. Defaults to apikey'
    required: true
    default: apikey
  user:
    description: 'Username for Artifactory. Must be supplied when credentials type is username'
    required: false
  password:
    description: 'Password for Artifactory. Must be supplied when credentials type is username'
    required: false
  apikey:
    description: 'Artifactory API Key. Must be supplied when credentials type is apikey'
    required: false
  access token:
    description: 'Artifactory access token. Must be supplied when credentials type is accesstoken'
    required: false
  config options:
    description: 'Add some option for "Adds a server configuration" command.'
    require: false
  working directory:
    description: 'Specify a working directory for the command to run in.'
    required: false
    default: .
branding:
  icon: 'package'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://advancedcsg/action-jfrog-cli:1'
