name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: create release
      uses: codfish/semantic-release-action@master
      if: success()
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      if: steps.version.outputs.new-release-published == 'true'
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image with release tag
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      if: steps.version.outputs.new-release-published == 'true'
      with:
        context: .
        push: true
        tags: ${{ steps.version.outputs.release-version }}

    - name: Build and push Docker image with major tag
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      if: steps.version.outputs.new-release-published == 'true'
      with:
        context: .
        push: true
        tags: ${{ steps.version.outputs.release-major }}

    - name: Build and push Docker image with latest tag
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      if: steps.version.outputs.new-release-published == 'true'
      with:
        context: .
        push: true
        tags: latest
